# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCTuzGKHUEa4B1j09LpIngaO1DfTyTan
"""

import streamlit as st
import pandas as pd
import random

def generate_random_data(num_groups):
    groups = []
    for i in range(1, num_groups + 1):
        group = {
            "Group Name": f"Group {i}",
            "Members": random.randint(5, 20),
            "Projects": random.randint(1, 5),
            "Average Rating": round(random.uniform(3.0, 5.0), 1)
        }
        groups.append(group)
    return pd.DataFrame(groups)

st.title("Group Information Dashboard")

# Sidebar for user input
st.sidebar.header("Dashboard Settings")
num_groups = st.sidebar.slider("Number of Groups", min_value=1, max_value=20, value=10)

# Generate random data
df = generate_random_data(num_groups)

# Display the data in a table
st.header("Group Overview")
st.dataframe(df)

# Display some statistics
st.header("Group Statistics")
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Total Groups", len(df))
with col2:
    st.metric("Total Members", df["Members"].sum())
with col3:
    st.metric("Average Rating", round(df["Average Rating"].mean(), 2))

# Display a bar chart of projects per group
st.header("Projects per Group")
st.bar_chart(df.set_index("Group Name")["Projects"])

# Display a line chart of average rating per group
st.header("Average Rating per Group")
st.line_chart(df.set_index("Group Name")["Average Rating"])

